name: Mirror
on: [schedule]
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: Mirroring Repository
    steps:
      - name: mirror-repository
        # You may pin to the exact commit or the version.
        # uses: yesolutions/mirror-action@082a9611ed4b64c796245a62b34584ee2ded6833
        uses: yesolutions/mirror-action@v0.6.0
        with:
          # The remote ref name to use. 'mirror' by default. Useful to avoid conflicts with existing remotes.
          REMOTE_NAME: https://codeberg.org/inhji/mirage # optional
          # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
          REMOTE: master # optional
          # Username for remote repository
          DEBUG: true # optional, default is false
